version: "3.8"

services:
    redis:
        image: redis:7.0.5-alpine3.16
        environment:
            - REDIS_PORT=${REDIS_PORT}
            - REDIS_HOST=${REDIS_HOST}
            - REDIS_PASSWORD=${REDIS_PASSWORD}
            - REDIS_DB=${REDIS_DB}
            - REDIS_POOL_SIZE=${REDIS_POOL_SIZE}
            - REDIS_EXPIRY_TIME=${REDIS_EXPIRY_TIME}
            - REDIS_HOST
        env_file:
            - .env

    postgres:
        image: postgres:15-alpine3.16
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}

        volumes:
            - pgdata:/var/lib/postgresql/data
        env_file:
            - .env
        ports:
            - "5433:5432"

    api:
        build:
            context: .
            dockerfile: Dockerfile
        # image: realtemirov/najottalim:latest
        ports:
            - "8000:8000"
        env_file:
            - .env
        environment:
            - POSTGRES_HOST=${POSTGRES_HOST}
            - POSTGRES_PORT=${POSTGRES_PORT}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        depends_on:
            - postgres
        restart: always

volumes:
    pgdata:
    redis: 
